"""shawarma_customizations: add column ingridients_id

Revision ID: 002c2541b7c1
Revises: 61e0023756ae
Create Date: 2025-05-07 08:43:29.933224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002c2541b7c1'
down_revision: Union[str, None] = '61e0023756ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shawarma_customizations', sa.Column('ingredient_id', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shawarma_customizations', 'ingredient_id')
    # ### end Alembic commands ###
