"""Create stryctyre database

Revision ID: 61e0023756ae
Revises: a71afa72a62e
Create Date: 2025-05-07 08:28:47.113472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e0023756ae'
down_revision: Union[str, None] = 'a71afa72a62e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_shop', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shawerma_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('base_ingredients', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shawerma_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shawerma_id'], ['shawerma_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_shawerma_id'), 'comments', ['shawerma_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('shawarma_customizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shawerma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shawerma_id'], ['shawerma_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shawarma_customizations_shawerma_id'), 'shawarma_customizations', ['shawerma_id'], unique=False)
    op.create_index(op.f('ix_shawarma_customizations_user_id'), 'shawarma_customizations', ['user_id'], unique=False)
    op.add_column('user_profile', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('user_profile', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'updated_at')
    op.drop_column('user_profile', 'created_at')
    op.drop_index(op.f('ix_shawarma_customizations_user_id'), table_name='shawarma_customizations')
    op.drop_index(op.f('ix_shawarma_customizations_shawerma_id'), table_name='shawarma_customizations')
    op.drop_table('shawarma_customizations')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_shawerma_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('shawerma_type')
    op.drop_table('locations')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
