"""empty message

Revision ID: a71afa72a62e
Revises: d3e1d03a384f
Create Date: 2025-04-30 20:06:50.645758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71afa72a62e'
down_revision: Union[str, None] = 'd3e1d03a384f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('login_attempts', sa.Integer(), nullable=False))
    op.add_column('user_profile', sa.Column('block_until', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'user_profile', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.drop_column('user_profile', 'block_until')
    op.drop_column('user_profile', 'login_attempts')
    # ### end Alembic commands ###
